"""add RFID attendance relation

Revision ID: 1b7301120b1d
Revises: d401905e1d01
Create Date: 2026-08-01 15:25:54.098188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1b7301120b1d'
down_revision: Union[str, Sequence[str], None] = 'd401905e1d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
