"""add zones and counters

Revision ID: 8aeb0792b17a
Revises: d106db42fcee
Create Date: 2026-08-01 03:38:45.716578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8aeb0792b17a'
down_revision: Union[str, Sequence[str], None] = 'd106db42fcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'number', name='uq_counter_agency_number')
    )
    op.create_index(op.f('ix_counters_agency_id'), 'counters', ['agency_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_agency_id'), 'zones', ['agency_id'], unique=False)
    op.add_column('agencies', sa.Column('opening_time', sa.Time(), nullable=True))
    op.add_column('agencies', sa.Column('closing_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'closing_time')
    op.drop_column('agencies', 'opening_time')
    op.drop_index(op.f('ix_zones_agency_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_counters_agency_id'), table_name='counters')
    op.drop_table('counters')
    # ### end Alembic commands ###
