"""add employee fields

Revision ID: c72e8e223212
Revises: 8aeb0792b17a
Create Date: 2026-08-01 13:07:02.550375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c72e8e223212'
down_revision: Union[str, Sequence[str], None] = '8aeb0792b17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    employee_status = sa.Enum(
        'ACTIVE',
        'INACTIVE',
        'ON_LEAVE',
        name='employeestatus',
    )
    employee_status.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column(
        'employees',
        sa.Column(
            'status',
            employee_status,
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
    )
    op.add_column('employees', sa.Column('hire_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'email')
    sa.Enum(
        'ACTIVE',
        'INACTIVE',
        'ON_LEAVE',
        name='employeestatus',
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
