"""link users and employees

Revision ID: d401905e1d01
Revises: c72e8e223212
Create Date: 2026-08-01 14:25:52.637200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd401905e1d01'
down_revision: Union[str, Sequence[str], None] = 'c72e8e223212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
