"""add ticket counter relation

Revision ID: deba57c577c1
Revises: 1b7301120b1d
Create Date: 2026-08-03 23:41:48.633406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'deba57c577c1'
down_revision: Union[str, Sequence[str], None] = '1b7301120b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('counter_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tickets_counter_id'), 'tickets', ['counter_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'counters', ['counter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_counter_id'), table_name='tickets')
    op.drop_column('tickets', 'counter_id')
    # ### end Alembic commands ###
